name: Create Release
description: Create a release in a project
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  version:
    description: 'Semantic version of the release (eg. v1.2.3 or v1.2.3-alpha.2)'
    required: true
  prev_version:
    description: 'Semantic version of the previous release (eg. v1.2.2 or v1.2.3-alpha.1)'
    required: false
    default: ''
  repository:
    description: 'The repository where the release should be created'
    required: false
    default: ${{ github.repository }}
  ref:
    description: 'The branch or SHA for the release (defaults to main)'
    required: false
    default: ${{ github.ref }}
  is_prerelease:
    description: 'Is this a pre-release?'
    required: false
    default: "false" 

runs:
  using: "composite"
  steps:
  - name: Verify tag is semver
    shell: bash
    run: |
      set -x
      if [[ ! "${{ inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$ ]]; then
        echo "This is not a semver compliant tag"
        echo "Exiting"
        exit 1
      fi

      if [[ "${{ inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        echo "is_prerelease=false" >> $GITHUB_OUTPUT
      else
        echo "is_prerelease=true" >> $GITHUB_OUTPUT
      fi

      if [[ "${{ inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.0$ ]]; then
        echo "is_dotzero=true" >> $GITHUB_OUTPUT
      else
        echo "is_dotzero=false" >> $GITHUB_OUTPUT
      fi

      XY_VERSION=$(echo ${{ inputs.version }} | awk -F. '{print substr($1,2)"."$2}')
      echo "xy_version=${XY_VERSION}" >> $GITHUB_OUTPUT
    id: check_tag

  - name: Checkout repository
    uses: actions/checkout@v4
    with:
      token: ${{ inputs.github_token }}
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}

  - name: Generate Changelog
    id: changelog
    env:
      GITHUB_TOKEN: ${{ inputs.github_token }}
    shell: bash
    run: |
      set -x

      REPOSITORY="${{ inputs.repository }}"
      SHA="$(git rev-parse HEAD)"
      echo "sha=${SHA}" >> "$GITHUB_OUTPUT"

      # Extract owner and repo name
      OWNER=$(echo "${REPOSITORY}" | cut -d'/' -f1)
      REPO=$(echo "${REPOSITORY}" | cut -d'/' -f2)
      echo "owner=${OWNER}" >> "$GITHUB_OUTPUT"
      echo "repo=${REPO}" >> "$GITHUB_OUTPUT"

      # Get the previous tag
      if [ -n "${{ inputs.prev_version }}" ] && git rev-list "${{ inputs.prev_version }}" 2> /dev/null; then
        PREV_TAG="${{ inputs.prev_version }}"
      else
        PREV_TAG=$(gh api -H "Accept: application/vnd.github+json" "/repos/${{ inputs.repository }}/releases/latest" | jq -r '.tag_name // empty')
      fi

      # Generate release notes
      NOTES=$(gh api --method POST \
        -H "Accept: application/vnd.github+json" \
        "/repos/${{ inputs.repository }}/releases/generate-notes" \
        -f tag_name="${{ inputs.version }}" \
        -f target_commitish="${SHA}" \
        -f previous_tag_name="${PREV_TAG}" | jq -r '.body')

      RELEASE_DOC="${PWD}/release.md"
      echo "**Full Changelog**: https://github.com/${REPOSITORY}/commits/${{ inputs.version }}" > "${RELEASE_DOC}"

      filterfunc() { echo "${NOTES}" | grep "^*\s*:$1:" | sed "s/.*:$1:\s*/* /"; }

      BREAKING_CHANGES="$(filterfunc warning)"
      if [ -n "${BREAKING_CHANGES}" ]; then
        { echo "## :warning: Breaking Changes"; echo "${BREAKING_CHANGES}"; echo ""; } >> "${RELEASE_DOC}"
      fi

      FEATURE_CHANGES="$(filterfunc sparkles)"
      if [ -n "${FEATURE_CHANGES}" ]; then
        { echo "## :sparkles: Features"; echo "${FEATURE_CHANGES}"; echo ""; } >> "${RELEASE_DOC}"
      fi

      BUG_FIXES="$(filterfunc bug)"
      if [ -n "${BUG_FIXES}" ]; then
        { echo "## :bug: Bug Fixes"; echo "${BUG_FIXES}"; echo ""; } >> "${RELEASE_DOC}"
      fi

      TEST_TUBES="$(filterfunc test_tube)"
      if [ -n "${TEST_TUBES}" ]; then
        { echo "## :test_tube: Integration or E2E tests"; echo "${TEST_TUBES}"; echo ""; } >> "${RELEASE_DOC}"
      fi

      NEW_CONTRIB=$(echo "${NOTES}" | sed -n "/Contributors/,\$p")
      if [ -n "${NEW_CONTRIB}" ]; then
        echo "${NEW_CONTRIB}" >> "${RELEASE_DOC}"
      else
        echo "${NOTES}" | sed -n "/Changelog/,\$p" >> "${RELEASE_DOC}"
      fi


  - uses: ncipollo/release-action@main
    with:
      owner: ${{ steps.changelog.outputs.owner }}
      repo: ${{ steps.changelog.outputs.repo }}
      tag: ${{ inputs.version }}
      commit: ${{ steps.changelog.outputs.sha }}
      bodyFile: release.md
      draft: false
      prerelease: ${{ inputs.is_prerelease }}
      skipIfReleaseExists: true
      token: ${{ inputs.github_token }}
