name: 'Synchronize Labels'
description: 'Synchronize Labels in Repository'
inputs:
  github_token:
    description: "the github_token provided by the actions runner"
    required: true
    type: string
  organization:
    description: "The organization"
    required: true
    type: string
  repository:
    description: "The repository"
    required: true
    type: string
runs:
  using: composite
  steps:
  - name: Set up Go
    uses: actions/setup-go@v3
  - name: See environment
    run: env
    shell: bash
  - name: Run verify
    env:
      GITHUB_TOKEN: ${{ inputs.github_token }}
    run: |
      cd ${GITHUB_ACTION_PATH}
      go mod download
      go run main.go -org ${{ inputs.organization }} -repo ${{ inputs.repository }}
    shell: bash
