name: Manage Milestone
description: Manage a Milestone in a Repository
inputs:
  github_token:
    description: "the github_token provided by the actions runner"
    required: true
    type: string
  organization:
    description: "The organization"
    required: true
    type: string
  repository:
    description: "The repository"
    required: true
    type: string
  title:
    description: Title of the milestone
    required: true
    type: string
  state:
    description: The state (open|closed) of the milestone
    required: true
    type: string
  description:
    description: Description of the milestone
    required: true
    type: string
  due:
    description: Due date (DateOnly format https://pkg.go.dev/time#pkg-constants)
    required: true
    type: string
runs:
  using: composite
  steps:
  - name: Set up Go
    uses: actions/setup-go@v3
  - name: See environment
    run: env
    shell: bash
  - name: Run action
    env:
      GITHUB_TOKEN: ${{ inputs.github_token }}
      ORGANIZATION: ${{ inputs.organization }}
      REPOSITORY: ${{ inputs.repository }}
      TITLE: ${{ inputs.title }}
      STATE: ${{ inputs.state }}
      DESCRIPTION: ${{ inputs.description }}
      DUE: ${{ inputs.due }}
    run: |
      cd ${GITHUB_ACTION_PATH}
      go mod download
      go run main.go
    shell: bash
