name: 'Verify PR'
description: 'Verify PRs for Konveyor organization'
inputs:
  github_token:
    description: "the github_token provided by the actions runner"
    required: true
runs:
  using: composite
  steps:
  - name: Set up Go
    uses: actions/setup-go@v5
  - name: Run verify
    run: cd ${GITHUB_ACTION_PATH} && go mod download && go run verify-pr.go
    shell: bash
