name: 'Verify PR'
description: 'Verify PRs for Konveyor organization'
inputs:
  github_token:
    description: "the github_token provided by the actions runner"
    required: true
runs:
  using: composite
  steps:
  - name: Set up Go
    uses: actions/setup-go@v3
  - name: Run verify
    run: go run ${GITHUB_ACTION_PATH}/verify-pr.go
    shell: bash
