name: PR tests

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      config: ${{ steps.filter.outputs.config }}
      milestone: ${{ steps.filter.outputs.milestone }}
      labels: ${{ steps.filter.outputs.labels }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            config:
              - "pkg/config/config.yaml"
            milestone:
              - "cmd/milestones/**"
            labels:
              - "cmd/labels/**"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go install github.com/rhysd/actionlint/cmd/actionlint@latest
      - run: |
          GOPATH="$(go env GOPATH)"
          export PATH="${PATH}:${GOPATH}/bin"
          actionlint

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go test ./...

  check-milestones:
    needs: build
    if: ${{ needs.build.outputs.config == 'true' || needs.build.outputs.milestone == 'true' }}
    runs-on: ubuntu-latest
    permissions: read-all
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      # - name: Get Token
      #   id: get_workflow_token
      #   uses: peter-murray/workflow-application-token-action@v3
      #   with:
      #     application_id: ${{ vars.KONVEYOR_BOT_ID }}
      #     application_private_key: ${{ secrets.KONVEYOR_BOT_KEY }}
      # - env:
      #     GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
      #   run: go run cmd/milestones/main.go -config pkg/config/config.yaml
      - run: go run cmd/milestones/main.go -config pkg/config/config.yaml -log-level 8

  check-labels:
    needs: build
    if: ${{ needs.build.outputs.config == 'true' || needs.build.outputs.milestone == 'true' }}
    runs-on: ubuntu-latest
    permissions: read-all
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      # - name: Get Token
      #   id: get_workflow_token
      #   uses: peter-murray/workflow-application-token-action@v3
      #   with:
      #     application_id: ${{ vars.KONVEYOR_BOT_ID }}
      #     application_private_key: ${{ secrets.KONVEYOR_BOT_KEY }}
      # - env:
      #     GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
      #   run: go run cmd/labels/main.go -config pkg/config/config.yaml
      - run: go run cmd/labels/main.go -config pkg/config/config.yaml
