name: PR verification

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify PR contents
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Title
        id: verifier
        uses: ./cmd/verify-pr
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
